### ISSUE TITLE
leakcanary检测，ActivityStackManager.currentContext 造成内存泄漏

### ISSUE THREAD

**Issue by Yihon** [RuffianZhong/Rx-Mvp#1]

**Comment by RuffianZhong** [comment]
@Yihon 我看了一下代码，确实是这样子的。
原因：
在项目的BaseActivity/BaseFragmentActivity的onResume中设置了currentContext，但是没有在onPause中清空它，导致的内存泄漏。
解决：
1.如果你的项目中不需要使用到currentContext，那么你可以在BaseXXX中去掉这个代码
2.自己在BaseXXX的onPause生命周期中设置currentContext=null;
