### ISSUE TITLE
添加自定义Interceptor在哪加

### ISSUE THREAD

**Issue by mingmingacc** [RuffianZhong/Rx-Mvp#12]
您好，添加自定义的Interceptor在哪修改，比如token

**Comment by RuffianZhong** [comment]
@mingmingacc 
你查看一下  RetrofitUtils > getOkHttpClientBase() 在这个方法可以添加 Interceptor，暂时没有提供接口动态添加

**Comment by RuffianZhong** [comment]
@mingmingacc 
你查看一下  RetrofitUtils > getOkHttpClientBase() 在这个方法可以添加 Interceptor，暂时没有提供接口动态添加
