### ISSUE TITLE
关于Token失效，跳转登录页面

### ISSUE THREAD

**Issue by mingmingacc** [RuffianZhong/Rx-Mvp#14]
您好，请问一下在Demo的RHttpCallback判断token失效后如何跳转到LoginActivity呢？比如startActivty
 switch (code) {
            case 101://token过期，跳转登录页面重新登录(示例)
                break;
            case 102://系统公告(示例)
                break;
            default:

**Comment by RuffianZhong** [comment]
@mingmingacc 
怎么跳转页面？startActivity就可以啦，你是说Context上下文怎么来吗？Application搞一个全局的，或者demo中的ActivityStackManager方式获取上下文也是可以的呀
