### ISSUE TITLE
add

### ISSUE THREAD

**Issue by xmlxin** [RuffianZhong/Rx-Mvp#15]

**Comment by xmlxin** [comment]
addHeader() 会重复两个

**Comment by xmlxin** [comment]
添加一个head会出现两个一样的head

**Comment by RuffianZhong** [comment]
@xmlxin 
addParameter() 表示添加参数，重复调用可叠加
setParameter() 表示重置参数，清空之前设置
RHttp.Configure.get().baseHeader(baseHeader)			//全局Header
这三个地方可以设置header 会不会重复添加了呢？或者把代码贴出来看看你是怎么添加header的？

**Comment by xmlxin** [comment]
找到原因了
![image](https://user-images.githubusercontent.com/13414044/55130829-574a4300-5157-11e9-8621-9716bf48fd5c.png)

**Comment by xmlxin** [comment]
拦截器 这里又重新设置了一遍head

**Comment by RuffianZhong** [comment]
@xmlxin 感谢反馈，确实存在重复添加header的问题。现在已经修复，同时之前的addHeader也存在问题，没有累加

**Comment by xmlxin** [comment]
不客气，感谢提供这么好用并且简洁的框架，
