### ISSUE TITLE
大神你好，用了你的框架，debug模式没问题，打包后进入mainActivity闪退，报错如下

### ISSUE THREAD

**Issue by JohnGreenn** [RuffianZhong/Rx-Mvp#20]
The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.reflect.UndeclaredThrowableException

知道什么原因吗？

**Comment by RuffianZhong** [comment]
@JohnGreenn 你参考readme中混淆相关的说明，看看是不是把你的实体类也混淆了，导致解析数据出错什么的（debug模式没问题，正式打包出错一般可以先考虑配置上的问题，混淆之类的）

**Comment by JohnGreenn** [comment]
谢谢大神的解答，的确是混淆出问题了，大神的框架很好用，狂赞~
