### ISSUE TITLE
取消网络请求这个在哪调用了啊

### ISSUE THREAD

**Issue by AndroidCloud** [RuffianZhong/Rx-Mvp#3]
public interface HttpRequestListener {
    void cancle();
}

**Comment by RuffianZhong** [comment]
@AndroidCloud 
`https://github.com/RuffianZhong/Rx-Mvp/blob/master/app/src/main/java/com/rx/mvp/cn/test/RetrofitTest.java
    //设置唯一TAG
    HttpRxObserver httpRxObserver = new HttpRxObserver(TAG + "login") {
        @override
        protected void onStart(Disposable d) {
        }
        @override
        protected void onError(ApiException e) {
        }
        @override
        protected void onSuccess(Object response) {
        }
    };
    new RetrofitTest().login(activity, account, psw).subscribe(httpRxObserver);

    //取消请求
    if(!httpRxObserver.isDisposed()){
        httpRxObserver.cancel();
    }`

**Comment by RuffianZhong** [comment]
@AndroidCloud 
1.手动取消的话参考
https://github.com/RuffianZhong/Rx-Mvp/blob/master/app/src/main/java/com/rx/mvp/cn/test/RetrofitTest.java
2.RxLifecycle2会根据生命周期自动取消网络请求 eg: onCreate(调用)->onStop(取消)
