### ISSUE TITLE
有一些界面比较简单，可以不采用mvp来实现，直接mvc就行了。

### ISSUE THREAD

**Issue by candebbs** [RuffianZhong/Rx-Mvp#7]
如题，能增加mvc的activity和franment

**Comment by RuffianZhong** [comment]
@candebbs 
如果说页面简单，可以直接常规实现，在activity中实现基础功能，该抽取的业务提取到业务类就可以了。
个人觉得没有必要再写MVCActivity。对于我来说，我会所有的页面都继承现在的MVPActivity，对应的P数组返回空就行了。（1.继承MVPActivity方便后续此页面增加复杂化功能，不用改框架；2.规范所有页面方便维护）
个人愚见，仅供参考
