### ISSUE TITLE
MVP模式？

### ISSUE THREAD

**Issue by Tester-1991** [RuffianZhong/Rx-Mvp#8]
UserBiz这个业务逻辑是否可以放置到Model层?作者把UserBiz这个类当成业务逻辑数据处理类，和业务相关，是否可以封装成Model层?另外BaseActivity各种基类方法，是否可以提供传递View的方法也就是setContentView方法不传递xml文件  传递view  因为目前项目用的都是自定义控件 不支持xml方式

**Comment by android-shiyan** [comment]
大佬，有qq吗？我有一些问题向您咨询和建议，谢谢。

**Comment by RuffianZhong** [comment]
@android-shiyan 632835821

**Comment by RuffianZhong** [comment]
@android-shiyan 
首先说明一点demo中的model是我分包的一个习惯，项目的所有模块的意思，并不是MVP中的M
1.UserBiz和XXBean这些可以任务是model层的东西，如果强迫症可以搞一个包名model放这些类，这个只是分包上的一点表现；
2.BaseActivity各种基类方法不是固定的，可以根据自己的需求做修改，如果你的项目传的是view，直接添加方法在基类中接收和处理view就可以了呀，其他几个方法无关紧要的，只是为了规范团队开发而已
